/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers, EventFilter, Signer, BigNumber, BigNumberish, PopulatedTransaction } from 'ethers'
import { Contract, ContractTransaction, Overrides, CallOverrides } from '@ethersproject/contracts'
import { BytesLike } from '@ethersproject/bytes'
import { Listener, Provider } from '@ethersproject/providers'
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi'

interface ERC721Interface extends ethers.utils.Interface {
  functions: {
    'name()': FunctionFragment
    'getApproved(uint256)': FunctionFragment
    'approve(address,uint256)': FunctionFragment
    'implementsERC721()': FunctionFragment
    'totalSupply()': FunctionFragment
    'transferFrom(address,address,uint256)': FunctionFragment
    'tokenOfOwnerByIndex(address,uint256)': FunctionFragment
    'ownerOf(uint256)': FunctionFragment
    'tokenMetadata(uint256)': FunctionFragment
    'balanceOf(address)': FunctionFragment
    'mint(address,uint256,address,string)': FunctionFragment
    'symbol()': FunctionFragment
    'transfer(address,uint256)': FunctionFragment
    'numTokensTotal()': FunctionFragment
    'getOwnerTokens(address)': FunctionFragment
  }

  encodeFunctionData(functionFragment: 'name', values?: undefined): string
  encodeFunctionData(functionFragment: 'getApproved', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'approve', values: [string, BigNumberish]): string
  encodeFunctionData(functionFragment: 'implementsERC721', values?: undefined): string
  encodeFunctionData(functionFragment: 'totalSupply', values?: undefined): string
  encodeFunctionData(functionFragment: 'transferFrom', values: [string, string, BigNumberish]): string
  encodeFunctionData(functionFragment: 'tokenOfOwnerByIndex', values: [string, BigNumberish]): string
  encodeFunctionData(functionFragment: 'ownerOf', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'tokenMetadata', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'balanceOf', values: [string]): string
  encodeFunctionData(functionFragment: 'mint', values: [string, BigNumberish, string, string]): string
  encodeFunctionData(functionFragment: 'symbol', values?: undefined): string
  encodeFunctionData(functionFragment: 'transfer', values: [string, BigNumberish]): string
  encodeFunctionData(functionFragment: 'numTokensTotal', values?: undefined): string
  encodeFunctionData(functionFragment: 'getOwnerTokens', values: [string]): string

  decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getApproved', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'implementsERC721', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'totalSupply', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'tokenOfOwnerByIndex', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'ownerOf', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'tokenMetadata', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'mint', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'transfer', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'numTokensTotal', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getOwnerTokens', data: BytesLike): Result

  events: {
    'Mint(address,uint256)': EventFragment
    'Transfer(address,address,uint256)': EventFragment
    'Approval(address,address,uint256)': EventFragment
  }

  getEvent(nameOrSignatureOrTopic: 'Mint'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'Transfer'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'Approval'): EventFragment
}

export class ERC721 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  on(event: EventFilter | string, listener: Listener): this
  once(event: EventFilter | string, listener: Listener): this
  addListener(eventName: EventFilter | string, listener: Listener): this
  removeAllListeners(eventName: EventFilter | string): this
  removeListener(eventName: any, listener: Listener): this

  interface: ERC721Interface

  functions: {
    name(overrides?: CallOverrides): Promise<[string] & { _name: string }>

    'name()'(overrides?: CallOverrides): Promise<[string] & { _name: string }>

    getApproved(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<[string] & { _approved: string }>

    'getApproved(uint256)'(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<[string] & { _approved: string }>

    approve(_to: string, _tokenId: BigNumberish, overrides?: Overrides): Promise<ContractTransaction>

    'approve(address,uint256)'(_to: string, _tokenId: BigNumberish, overrides?: Overrides): Promise<ContractTransaction>

    implementsERC721(overrides?: CallOverrides): Promise<[boolean] & { _implementsERC721: boolean }>

    'implementsERC721()'(overrides?: CallOverrides): Promise<[boolean] & { _implementsERC721: boolean }>

    totalSupply(overrides?: CallOverrides): Promise<[BigNumber] & { _totalSupply: BigNumber }>

    'totalSupply()'(overrides?: CallOverrides): Promise<[BigNumber] & { _totalSupply: BigNumber }>

    transferFrom(
      _from: string,
      _to: string,
      _tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>

    'transferFrom(address,address,uint256)'(
      _from: string,
      _to: string,
      _tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>

    tokenOfOwnerByIndex(
      _owner: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _tokenId: BigNumber }>

    'tokenOfOwnerByIndex(address,uint256)'(
      _owner: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _tokenId: BigNumber }>

    ownerOf(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<[string] & { _owner: string }>

    'ownerOf(uint256)'(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<[string] & { _owner: string }>

    tokenMetadata(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<[string] & { _infoUrl: string }>

    'tokenMetadata(uint256)'(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { _infoUrl: string }>

    balanceOf(_owner: string, overrides?: CallOverrides): Promise<[BigNumber] & { _balance: BigNumber }>

    'balanceOf(address)'(_owner: string, overrides?: CallOverrides): Promise<[BigNumber] & { _balance: BigNumber }>

    mint(
      _owner: string,
      _tokenId: BigNumberish,
      _approvedAddress: string,
      _metadata: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>

    'mint(address,uint256,address,string)'(
      _owner: string,
      _tokenId: BigNumberish,
      _approvedAddress: string,
      _metadata: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>

    symbol(overrides?: CallOverrides): Promise<[string] & { _symbol: string }>

    'symbol()'(overrides?: CallOverrides): Promise<[string] & { _symbol: string }>

    transfer(_to: string, _tokenId: BigNumberish, overrides?: Overrides): Promise<ContractTransaction>

    'transfer(address,uint256)'(
      _to: string,
      _tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>

    numTokensTotal(overrides?: CallOverrides): Promise<[BigNumber]>

    'numTokensTotal()'(overrides?: CallOverrides): Promise<[BigNumber]>

    getOwnerTokens(_owner: string, overrides?: CallOverrides): Promise<[BigNumber[]] & { _tokenIds: BigNumber[] }>

    'getOwnerTokens(address)'(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]] & { _tokenIds: BigNumber[] }>
  }

  name(overrides?: CallOverrides): Promise<string>

  'name()'(overrides?: CallOverrides): Promise<string>

  getApproved(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>

  'getApproved(uint256)'(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>

  approve(_to: string, _tokenId: BigNumberish, overrides?: Overrides): Promise<ContractTransaction>

  'approve(address,uint256)'(_to: string, _tokenId: BigNumberish, overrides?: Overrides): Promise<ContractTransaction>

  implementsERC721(overrides?: CallOverrides): Promise<boolean>

  'implementsERC721()'(overrides?: CallOverrides): Promise<boolean>

  totalSupply(overrides?: CallOverrides): Promise<BigNumber>

  'totalSupply()'(overrides?: CallOverrides): Promise<BigNumber>

  transferFrom(_from: string, _to: string, _tokenId: BigNumberish, overrides?: Overrides): Promise<ContractTransaction>

  'transferFrom(address,address,uint256)'(
    _from: string,
    _to: string,
    _tokenId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>

  tokenOfOwnerByIndex(_owner: string, _index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

  'tokenOfOwnerByIndex(address,uint256)'(
    _owner: string,
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>

  ownerOf(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>

  'ownerOf(uint256)'(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>

  tokenMetadata(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>

  'tokenMetadata(uint256)'(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>

  balanceOf(_owner: string, overrides?: CallOverrides): Promise<BigNumber>

  'balanceOf(address)'(_owner: string, overrides?: CallOverrides): Promise<BigNumber>

  mint(
    _owner: string,
    _tokenId: BigNumberish,
    _approvedAddress: string,
    _metadata: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>

  'mint(address,uint256,address,string)'(
    _owner: string,
    _tokenId: BigNumberish,
    _approvedAddress: string,
    _metadata: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>

  symbol(overrides?: CallOverrides): Promise<string>

  'symbol()'(overrides?: CallOverrides): Promise<string>

  transfer(_to: string, _tokenId: BigNumberish, overrides?: Overrides): Promise<ContractTransaction>

  'transfer(address,uint256)'(_to: string, _tokenId: BigNumberish, overrides?: Overrides): Promise<ContractTransaction>

  numTokensTotal(overrides?: CallOverrides): Promise<BigNumber>

  'numTokensTotal()'(overrides?: CallOverrides): Promise<BigNumber>

  getOwnerTokens(_owner: string, overrides?: CallOverrides): Promise<BigNumber[]>

  'getOwnerTokens(address)'(_owner: string, overrides?: CallOverrides): Promise<BigNumber[]>

  callStatic: {
    name(overrides?: CallOverrides): Promise<string>

    'name()'(overrides?: CallOverrides): Promise<string>

    getApproved(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>

    'getApproved(uint256)'(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>

    approve(_to: string, _tokenId: BigNumberish, overrides?: CallOverrides): Promise<void>

    'approve(address,uint256)'(_to: string, _tokenId: BigNumberish, overrides?: CallOverrides): Promise<void>

    implementsERC721(overrides?: CallOverrides): Promise<boolean>

    'implementsERC721()'(overrides?: CallOverrides): Promise<boolean>

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>

    'totalSupply()'(overrides?: CallOverrides): Promise<BigNumber>

    transferFrom(_from: string, _to: string, _tokenId: BigNumberish, overrides?: CallOverrides): Promise<void>

    'transferFrom(address,address,uint256)'(
      _from: string,
      _to: string,
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>

    tokenOfOwnerByIndex(_owner: string, _index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    'tokenOfOwnerByIndex(address,uint256)'(
      _owner: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    ownerOf(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>

    'ownerOf(uint256)'(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>

    tokenMetadata(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>

    'tokenMetadata(uint256)'(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>

    balanceOf(_owner: string, overrides?: CallOverrides): Promise<BigNumber>

    'balanceOf(address)'(_owner: string, overrides?: CallOverrides): Promise<BigNumber>

    mint(
      _owner: string,
      _tokenId: BigNumberish,
      _approvedAddress: string,
      _metadata: string,
      overrides?: CallOverrides
    ): Promise<void>

    'mint(address,uint256,address,string)'(
      _owner: string,
      _tokenId: BigNumberish,
      _approvedAddress: string,
      _metadata: string,
      overrides?: CallOverrides
    ): Promise<void>

    symbol(overrides?: CallOverrides): Promise<string>

    'symbol()'(overrides?: CallOverrides): Promise<string>

    transfer(_to: string, _tokenId: BigNumberish, overrides?: CallOverrides): Promise<void>

    'transfer(address,uint256)'(_to: string, _tokenId: BigNumberish, overrides?: CallOverrides): Promise<void>

    numTokensTotal(overrides?: CallOverrides): Promise<BigNumber>

    'numTokensTotal()'(overrides?: CallOverrides): Promise<BigNumber>

    getOwnerTokens(_owner: string, overrides?: CallOverrides): Promise<BigNumber[]>

    'getOwnerTokens(address)'(_owner: string, overrides?: CallOverrides): Promise<BigNumber[]>
  }

  filters: {
    Mint(_to: string | null, _tokenId: BigNumberish | null): EventFilter

    Transfer(_from: string | null, _to: string | null, _tokenId: null): EventFilter

    Approval(_owner: string | null, _approved: string | null, _tokenId: null): EventFilter
  }

  estimateGas: {
    name(overrides?: CallOverrides): Promise<BigNumber>

    'name()'(overrides?: CallOverrides): Promise<BigNumber>

    getApproved(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    'getApproved(uint256)'(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    approve(_to: string, _tokenId: BigNumberish, overrides?: Overrides): Promise<BigNumber>

    'approve(address,uint256)'(_to: string, _tokenId: BigNumberish, overrides?: Overrides): Promise<BigNumber>

    implementsERC721(overrides?: CallOverrides): Promise<BigNumber>

    'implementsERC721()'(overrides?: CallOverrides): Promise<BigNumber>

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>

    'totalSupply()'(overrides?: CallOverrides): Promise<BigNumber>

    transferFrom(_from: string, _to: string, _tokenId: BigNumberish, overrides?: Overrides): Promise<BigNumber>

    'transferFrom(address,address,uint256)'(
      _from: string,
      _to: string,
      _tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>

    tokenOfOwnerByIndex(_owner: string, _index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    'tokenOfOwnerByIndex(address,uint256)'(
      _owner: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    ownerOf(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    'ownerOf(uint256)'(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    tokenMetadata(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    'tokenMetadata(uint256)'(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    balanceOf(_owner: string, overrides?: CallOverrides): Promise<BigNumber>

    'balanceOf(address)'(_owner: string, overrides?: CallOverrides): Promise<BigNumber>

    mint(
      _owner: string,
      _tokenId: BigNumberish,
      _approvedAddress: string,
      _metadata: string,
      overrides?: Overrides
    ): Promise<BigNumber>

    'mint(address,uint256,address,string)'(
      _owner: string,
      _tokenId: BigNumberish,
      _approvedAddress: string,
      _metadata: string,
      overrides?: Overrides
    ): Promise<BigNumber>

    symbol(overrides?: CallOverrides): Promise<BigNumber>

    'symbol()'(overrides?: CallOverrides): Promise<BigNumber>

    transfer(_to: string, _tokenId: BigNumberish, overrides?: Overrides): Promise<BigNumber>

    'transfer(address,uint256)'(_to: string, _tokenId: BigNumberish, overrides?: Overrides): Promise<BigNumber>

    numTokensTotal(overrides?: CallOverrides): Promise<BigNumber>

    'numTokensTotal()'(overrides?: CallOverrides): Promise<BigNumber>

    getOwnerTokens(_owner: string, overrides?: CallOverrides): Promise<BigNumber>

    'getOwnerTokens(address)'(_owner: string, overrides?: CallOverrides): Promise<BigNumber>
  }

  populateTransaction: {
    name(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'name()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    getApproved(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    'getApproved(uint256)'(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    approve(_to: string, _tokenId: BigNumberish, overrides?: Overrides): Promise<PopulatedTransaction>

    'approve(address,uint256)'(
      _to: string,
      _tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    implementsERC721(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'implementsERC721()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    totalSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'totalSupply()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    transferFrom(
      _from: string,
      _to: string,
      _tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    'transferFrom(address,address,uint256)'(
      _from: string,
      _to: string,
      _tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    tokenOfOwnerByIndex(_owner: string, _index: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    'tokenOfOwnerByIndex(address,uint256)'(
      _owner: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    ownerOf(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    'ownerOf(uint256)'(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    tokenMetadata(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    'tokenMetadata(uint256)'(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    balanceOf(_owner: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

    'balanceOf(address)'(_owner: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

    mint(
      _owner: string,
      _tokenId: BigNumberish,
      _approvedAddress: string,
      _metadata: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    'mint(address,uint256,address,string)'(
      _owner: string,
      _tokenId: BigNumberish,
      _approvedAddress: string,
      _metadata: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    symbol(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'symbol()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    transfer(_to: string, _tokenId: BigNumberish, overrides?: Overrides): Promise<PopulatedTransaction>

    'transfer(address,uint256)'(
      _to: string,
      _tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    numTokensTotal(overrides?: CallOverrides): Promise<PopulatedTransaction>

    'numTokensTotal()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

    getOwnerTokens(_owner: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

    'getOwnerTokens(address)'(_owner: string, overrides?: CallOverrides): Promise<PopulatedTransaction>
  }
}
