/* Autogenerated file. Do not edit manually. */
/* tslint:disable */

import { Provider } from '@ethersproject/providers'
import { Contract, Signer } from 'ethers'

/* eslint-disable */
export type { ERC20 } from './ERC20'
export type { ERC721 } from './ERC721'
export type { LendingPool } from './LendingPool'
export type { LoanManager } from './LoanManager'

export { ERC20Factory } from './factories/ERC20__factory'
export { ERC721Factory } from './factories/ERC721__factory'
export { LendingPoolFactory } from './factories/LendingPool__factory'
export { LoanManagerFactory } from './factories/LoanManager__factory'

export class DebtTokenFactory {
  static connect(address: string, signerOrProvider: Signer | Provider) {
    return new Contract(address, _DebtTokenFactory, signerOrProvider)
  }
}

const _DebtTokenFactory = [
  'function approveDelegation(address delegatee, uint256 amount) external',
  'function balanceOf(address account) public view returns (uint256)',
]
